---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-mcp-server
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/containers/charts/kubernetes-mcp-server
      targetRevision: 0.1.0
      path: .
      helm:
        valueFiles:
          - $values/manifests/mcp/kubernetes-mcp/values.yaml
    - repoURL: https://github.com/pdavis327/rhoai-3.3-cluster
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: mcp-demo
  syncPolicy:
    automated: {}
    syncOptions: 
      - CreateNamespace=true