apiVersion: v1
kind: Namespace
metadata:
  name: whisper-demo
  labels:
    opendatahub.io/dashboard: 'true'
    kueue.openshift.io/managed: 'true'
    modelmesh-enabled: 'false'
  annotations:
    openshift.io/display-name: whisper-demo
    openshift.io/description: ''
