apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whisper-live-caption
    kueue.x-k8s.io/queue-name: default
  name: whisper-live-caption
  namespace: whisper-demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: whisper-live-caption
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-09-01T11:56:49-04:00'
        kueue.x-k8s.io/pod-suspending-parent: deployment
      creationTimestamp: null
      labels:
        app: whisper-live-caption
        kueue.x-k8s.io/managed: 'true'
        kueue.x-k8s.io/queue-name: default
    spec:
      containers:
      - env:
        - name: WHISPER_VERIFY_SSL
          value: 'false'
        envFrom:
        - secretRef:
            name: whisper-live-caption
        image: quay.io/rh-ee-petdavis/whisper-live-caption:6
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: live-caption
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: whisper-live-caption
      serviceAccountName: whisper-live-caption
      terminationGracePeriodSeconds: 30
