apiVersion: v1
imagePullSecrets:
- name: whisper-live-caption-dockercfg-fkpqx
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: whisper-live-caption-dockercfg-fkpqx
  labels:
    app: whisper-live-caption
  name: whisper-live-caption
  namespace: whisper-demo
secrets:
- name: whisper-live-caption-dockercfg-fkpqx
