apiVersion: v1
data:
  GITHUB_API_URL: https://api.github.com
  LLM_BASE_URL: https://APPS_DOMAIN/v1
  LLM_MODEL_ID: redhataigpt-oss-20b
  LLM_PROVIDER_ID: openshift-ai
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: code-reviewer-pipeline
  name: code-reviewer-pipeline-config
  namespace: code-reviewer
