apiVersion: v1
data:
  GITHUB_API_URL: https://api.github.com
  LLM_BASE_URL: https://llama-3-2-1b-instruct-kserve-workload-svc.model-server.svc.cluster.local:8000/v1
  LLM_MODEL_ID: meta-llama/llama-3.2-1b-instruct
  LLM_PROVIDER_ID: openshift-ai
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: code-reviewer-pipeline
  name: code-reviewer-pipeline-config
  namespace: code-reviewer
