apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: code-reviewer
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: code-reviewer-pipeline
    helm.sh/chart: code-reviewer-pipeline-0.1.0
  name: code-reviewer-pipeline-job-manager
  namespace: code-reviewer
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
