apiVersion: v1
imagePullSecrets:
- name: code-reviewer-dockercfg-jht78
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: code-reviewer-dockercfg-jht78
  labels:
    app.kubernetes.io/name: code-reviewer-pipeline
  name: code-reviewer
  namespace: code-reviewer
secrets:
- name: code-reviewer-dockercfg-jht78
