apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: listener
    app.kubernetes.io/name: code-reviewer-pipeline
  name: code-reviewer-pipeline-listener
  namespace: code-reviewer
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: listener
    app.kubernetes.io/name: code-reviewer-pipeline
  type: ClusterIP
