apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-gemma4
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/pdavis327/rhoai-3.x-cluster
    targetRevision: main
    path: projects/gemma4
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gemma4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true

  ignoreDifferences:
  - group: kubeflow.org
    kind: Notebook
    jqPathExpressions:
    - .metadata.annotations["notebooks.opendatahub.io/update-pending"]
    - .metadata.annotations["notebooks.opendatahub.io/last-image-selection"]
    - .spec.template.spec.containers[] | select(.name == "kube-rbac-proxy")
    - .spec.template.spec.containers[].env[]? | select(.name == "MLFLOW_TRACKING_URI")
    - .spec.template.spec.containers[].env[]? | select(.name == "MLFLOW_K8S_INTEGRATION")
    - .spec.template.spec.containers[].env[]? | select(.name == "MLFLOW_TRACKING_AUTH")
    - .status
