apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-whisper-demo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/pdavis327/rhoai-3.x-cluster
    targetRevision: main
    path: projects/whisper-demo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: whisper-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - SkipDryRunOnMissingResource=true
    - RespectIgnoreDifferences=true
