apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maas-postgresql-data
  namespace: models-as-service-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
