apiVersion: v1
kind: Service
metadata:
  name: maas-postgresql
  namespace: models-as-service-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: maas-postgresql
  type: ClusterIP
