apiVersion: v1
data:
  MLFLOW_TRACKING_AUTH: kubernetes-namespaced
  MLFLOW_TRACKING_URI: https://mlflow.redhat-ods-applications.svc:8443/mlflow
kind: ConfigMap
metadata:
  labels:
    opendatahub.io/dashboard: 'true'
  name: configmap-jmjttk
  namespace: gemma4
