apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-testing-storage
  namespace: gemma4
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
