apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: kubernetes.io/arch=amd64
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "65536"
    machine.openshift.io/vCPU: "16"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-rkdbh-jxxs9
  name: cluster-rkdbh-jxxs9-worker-us-east-2c-gpu-g6xlarge
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-rkdbh-jxxs9
      machine.openshift.io/cluster-api-machineset: cluster-rkdbh-jxxs9-worker-us-east-2c-gpu-g6xlarge
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-rkdbh-jxxs9
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-rkdbh-jxxs9-worker-us-east-2c-gpu-g6xlarge
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-0fd7c367ed8a90d52
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: gp2
          capacityReservationId: ""
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-rkdbh-jxxs9-worker-profile
          instanceType: g6.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-rkdbh-jxxs9-node
          - filters:
            - name: tag:Name
              values:
              - cluster-rkdbh-jxxs9-lb
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-rkdbh-jxxs9-subnet-private-us-east-2c
          tags:
          - name: kubernetes.io/cluster/cluster-rkdbh-jxxs9
            value: owned
          - name: Stack
            value: project ocp4-cluster-rkdbh
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: rkdbh
          - name: owner
            value: unknown
          - name: platform
            value: RHPDS
          - name: uuid
            value: c0952349-bd9c-598e-b9e0-92390c0c4344
          userDataSecret:
            name: worker-user-data
status:
