apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-cluster-config
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/pdavis327/rhoai-3.x-cluster
    targetRevision: main
    path: cluster-config
    directory:
      recurse: true
      exclude: '{**/README.md,maas-gateway/**}'
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
