apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-maas-gateway
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/pdavis327/rhoai-3.x-cluster
    targetRevision: main
    path: cluster-config/maas-gateway
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
