apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: elasticsearch
  name: data-self-service-agent-elasticsearch-master-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: postgresql
  name: data-self-service-agent-postgresql-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: redis
  name: data-self-service-agent-redis-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: pgvector
  name: pg-data-pgvector-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
