apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-48-54.us-east-2.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: elasticsearch
  name: data-self-service-agent-elasticsearch-master-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-9-241.us-east-2.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: postgresql
  name: data-self-service-agent-postgresql-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-9-241.us-east-2.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: redis
  name: data-self-service-agent-redis-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: llama-stack-data
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-9-241.us-east-2.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/instance: self-service-agent
    app.kubernetes.io/name: pgvector
  name: pg-data-pgvector-0
  namespace: ticket-resolution
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
