apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: self-service-agent-dockercfg-jhwkk
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: self-service-agent-dockercfg-jhwkk
  labels:
    app.kubernetes.io/name: self-service-agent
  name: self-service-agent
  namespace: ticket-resolution
secrets:
- name: self-service-agent-dockercfg-jhwkk
---
apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: self-service-agent-elasticsearch-master-dockercfg-5fhk6
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: self-service-agent-elasticsearch-master-dockercfg-5fhk6
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/name: elasticsearch
  name: self-service-agent-elasticsearch-master
  namespace: ticket-resolution
secrets:
- name: self-service-agent-elasticsearch-master-dockercfg-5fhk6
---
apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: self-service-agent-memcached-dockercfg-ccb24
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: self-service-agent-memcached-dockercfg-ccb24
  labels:
    app.kubernetes.io/name: memcached
  name: self-service-agent-memcached
  namespace: ticket-resolution
secrets:
- name: self-service-agent-memcached-dockercfg-ccb24
---
apiVersion: v1
automountServiceAccountToken: false
imagePullSecrets:
- name: self-service-agent-postgresql-dockercfg-6wkj4
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: self-service-agent-postgresql-dockercfg-6wkj4
  labels:
    app.kubernetes.io/name: postgresql
  name: self-service-agent-postgresql
  namespace: ticket-resolution
secrets:
- name: self-service-agent-postgresql-dockercfg-6wkj4
---
apiVersion: v1
imagePullSecrets:
- name: self-service-agent-zammad-bootstrap-dockercfg-lrxzl
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: '5'
    openshift.io/internal-registry-pull-secret-ref: self-service-agent-zammad-bootstrap-dockercfg-lrxzl
  labels:
    app.kubernetes.io/component: zammad-bootstrap
  name: self-service-agent-zammad-bootstrap
  namespace: ticket-resolution
secrets:
- name: self-service-agent-zammad-bootstrap-dockercfg-lrxzl
