apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: 'true'
    notebooks.opendatahub.io/last-image-selection: pytorch:2025.2
    notebooks.opendatahub.io/last-image-version-git-commit-selection: 8e73cac
    opendatahub.io/connections: ''
    opendatahub.io/hardware-profile-name: nvidia-l40s
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-resource-version: '77734'
    opendatahub.io/image-display-name: Jupyter | PyTorch | CUDA | Python 3.12
    opendatahub.io/mlflow-instance: mlflow
    opendatahub.io/username: petedavis
    kubeflow-resource-stopped: 'true'
    openshift.io/description: Stopped on this cluster because the single GPU is assigned to the MaaS llama model. Remove kubeflow-resource-stopped to start after scaling llama to 0.
    openshift.io/display-name: fine tuning
  labels:
    app: fine-tuning
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: petedavis
  name: fine-tuning
  namespace: fine-tuning
spec:
  template:
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: "--ServerApp.port=8888\n                  --ServerApp.token=''\n                  --ServerApp.password=''\n\
            \                  --ServerApp.base_url=/notebook/fine-tuning/fine-tuning\n                  --ServerApp.quit_button=False"
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.2
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: KF_PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: MLFLOW_K8S_INTEGRATION
          value: 'true'
        - name: MLFLOW_TRACKING_AUTH
          value: kubernetes-namespaced
        - name: MLFLOW_TRACKING_URI
          value: https://rh-ai.apps.ocp.cjrcx.sandbox1524.opentlc.com/mlflow
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/pytorch:2025.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/fine-tuning/fine-tuning/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: fine-tuning
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/fine-tuning/fine-tuning/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '12'
            memory: 48Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '12'
            memory: 48Gi
            nvidia.com/gpu: '1'
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: fine-tuning-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs
          name: trusted-ca
          readOnly: true
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8888/
        - --logtostderr=true
        - --v=0
        - --proxy-endpoints-port=8444
        - --config-file=/etc/kube-rbac-proxy/config-file.yaml
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --auth-header-fields-enabled=true
        - --auth-header-user-field-name=X-Auth-Request-User
        - --auth-header-groups-field-name=X-Auth-Request-Groups
        image: registry.redhat.io/rhoai/odh-kube-rbac-proxy-rhel9@sha256:b64105d53ab3f7d477652b2f29c90636fe272891cce71620ceadf0bf2eb3e323
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: kube-rbac-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/kube-rbac-proxy
          name: kube-rbac-proxy-config
        - mountPath: /etc/tls/private
          name: kube-rbac-proxy-tls-certificates
      enableServiceLinks: false
      serviceAccountName: fine-tuning
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: largegpu
        operator: Exists
      volumes:
      - name: fine-tuning-storage
        persistentVolumeClaim:
          claimName: fine-tuning-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
      - configMap:
          defaultMode: 420
          name: fine-tuning-kube-rbac-proxy-config
        name: kube-rbac-proxy-config
      - name: kube-rbac-proxy-tls-certificates
        secret:
          defaultMode: 420
          secretName: fine-tuning-kube-rbac-proxy-tls
