apiVersion: v1
kind: Namespace
metadata:
  name: model-server
  labels:
    opendatahub.io/dashboard: 'true'
    modelmesh-enabled: 'false'
    maas.opendatahub.io/gateway-access: 'true'
    maas-gateway-access: 'true'
