apiVersion: v1
kind: Namespace
metadata:
  name: code-assistant
  labels:
    opendatahub.io/dashboard: 'true'
    modelmesh-enabled: 'false'
  annotations:
    openshift.io/display-name: code-assistant
    openshift.io/description: ''
