apiVersion: mcp.x-k8s.io/v1alpha1
kind: MCPServer
metadata:
  annotations:
    mcp.opendatahub.io/catalog-server: openshift-mcp-server
    mcp.opendatahub.io/display-name: openshift-mcp
  name: openshift-mcp
  namespace: code-assistant
spec:
  config:
    arguments:
    - --config
    - /etc/mcp-config/config.toml
    path: /mcp
    port: 8080
    storage:
    - path: /etc/mcp-config
      permissions: ReadOnly
      source:
        configMap:
          name: openshift-mcp-server-config
        type: ConfigMap
  runtime:
    security:
      serviceAccountName: mcp-viewer
  source:
    containerImage:
      ref: registry.redhat.io/openshift-mcp-tech-preview/openshift-mcp-server-rhel9:0.4
    type: ContainerImage
