apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-storage
  namespace: code-assistant
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
