apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-19-0.us-east-2.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    gen-ai.opendatahub.io/pgvector: 'true'
  name: genai-pgvector-storage
  namespace: code-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-51-9.us-east-2.compute.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  name: trustyai-service-pvc
  namespace: code-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
