apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    gen-ai.opendatahub.io/pgvector: 'true'
  name: genai-pgvector-storage
  namespace: code-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trustyai-service-pvc
  namespace: code-assistant
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
