apiVersion: v1
kind: Service
metadata:
  labels:
    gen-ai.opendatahub.io/pgvector: 'true'
  name: genai-pgvector
  namespace: code-assistant
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: genai-pgvector
    gen-ai.opendatahub.io/pgvector: 'true'
  type: ClusterIP
