apiVersion: v1
kind: Namespace
metadata:
  name: country-of-origin-predictor
  labels:
    opendatahub.io/dashboard: 'true'
    modelmesh-enabled: 'false'
  annotations:
    openshift.io/display-name: country-of-origin-predictor
