apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: country-of-origin-predictor
spec:
  apiServer:
    artifactSignedURLExpirySeconds: 60
    caBundleFileMountPath: ''
    caBundleFileName: ''
    cacheEnabled: true
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    managedPipelines: {}
    pipelineStore: kubernetes
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ''
      bucket: coo-predictor
      host: minio-service.country-of-origin-predictor.svc
      port: '9000'
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
