apiVersion: v1
imagePullSecrets:
- name: pipeline-runner-dspa-dockercfg-jnnmh
kind: ServiceAccount
metadata:
  annotations:
    manifestival: new
    openshift.io/internal-registry-pull-secret-ref: pipeline-runner-dspa-dockercfg-jnnmh
  labels:
    app: ds-pipeline-dspa
    component: data-science-pipelines
    dsp-version: v2
  name: pipeline-runner-dspa
  namespace: country-of-origin-predictor
secrets:
- name: pipeline-runner-dspa-dockercfg-jnnmh
