apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  components:
    aipipelines:
      argoWorkflowsControllers:
        managementState: Managed
      managementState: Managed
    dashboard:
      managementState: Managed
    feastoperator:
      managementState: Managed
    mlflowoperator:
      managementState: Managed
    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Managed
      nim:
        managementState: Managed
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
      managementState: Removed
    llamastackoperator:
      managementState: Managed
    modelregistry:
      managementState: Managed
      registriesNamespace: rhoai-model-registries
    ray:
      managementState: Managed
    trainingoperator:
      managementState: Managed
    trustyai:
      managementState: Managed
      eval:
        lmeval:
           permitOnline: allow
           permitCodeExecution: allow
    workbenches:
      managementState: Managed
      workbenchNamespace: rhods-notebooks
