apiVersion: v1
items:
- apiVersion: mlflow.opendatahub.io/v1
  kind: MLflow
  metadata:
    name: mlflow
  spec:
    backendStoreUri: "sqlite:////mlflow/mlflow.db"
    artifactsDestination: "s3://rhoai/mlflow/artifacts"
    serveArtifacts: true
    envFrom:
      - secretRef:
          name: mlflow-artifact-s3
    replicas: 1
    serveArtifacts: true
    serviceAccountName: mlflow-sa
    storage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
    workers: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
