apiVersion: v1
kind: Namespace
metadata:
  name: ray-workshop
  labels:
    opendatahub.io/dashboard: 'true'
    kueue.openshift.io/managed: 'true'
  annotations:
    openshift.io/display-name: Ray Workshop
    openshift.io/description: Hands-on Ray, CodeFlare, KubeRay, and Kueue workshop
