apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ray-lab-storage
  namespace: ray-workshop
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
