apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: 'true'
    notebooks.opendatahub.io/last-image-selection: s2i-generic-data-science-notebook:3.4
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    opendatahub.io/connections: ''
    opendatahub.io/hardware-profile-name: cpu-local-queue
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/hardware-profile-resource-version: '173229862'
    opendatahub.io/image-display-name: Jupyter | Data Science | CPU | Python 3.12
    opendatahub.io/mlflow-instance: mlflow
    opendatahub.io/user: petedavis
    opendatahub.io/username: petedavis
    opendatahub.io/workbench-image-namespace: ''
    openshift.io/description: ''
    openshift.io/display-name: ray-lab
  labels:
    app: ray-lab
    kueue.x-k8s.io/queue-name: default
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
  name: ray-lab
  namespace: ray-workshop
spec:
  template:
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: "--ServerApp.port=8888\n                  --ServerApp.token=''\n                  --ServerApp.password=''\n\
            \                  --ServerApp.base_url=/notebook/ray-workshop/ray-lab\n                  --ServerApp.quit_button=False"
        - name: JUPYTER_IMAGE
          value: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:3.4
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: KF_PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: MLFLOW_K8S_INTEGRATION
          value: 'true'
        - name: MLFLOW_TRACKING_AUTH
          value: kubernetes-namespaced
        - name: MLFLOW_TRACKING_URI
          value: https://rh-ai.apps.ocp.cjrcx.sandbox1524.opentlc.com/mlflow
        image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:3.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/ray-workshop/ray-lab/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: ray-lab
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/ray-workshop/ray-lab/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
          requests:
            cpu: '2'
            memory: 8Gi
        volumeMounts:
        - mountPath: /opt/app-root/src/
          name: ray-lab-storage
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs
          name: trusted-ca
          readOnly: true
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8888/
        - --logtostderr=true
        - --v=0
        - --proxy-endpoints-port=8444
        - --config-file=/etc/kube-rbac-proxy/config-file.yaml
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --auth-header-fields-enabled=true
        - --auth-header-user-field-name=X-Auth-Request-User
        - --auth-header-groups-field-name=X-Auth-Request-Groups
        image: registry.redhat.io/rhoai/odh-kube-rbac-proxy-rhel9@sha256:b64105d53ab3f7d477652b2f29c90636fe272891cce71620ceadf0bf2eb3e323
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: kube-rbac-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8444
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /etc/kube-rbac-proxy
          name: kube-rbac-proxy-config
        - mountPath: /etc/tls/private
          name: kube-rbac-proxy-tls-certificates
      enableServiceLinks: false
      serviceAccountName: ray-lab
      volumes:
      - name: ray-lab-storage
        persistentVolumeClaim:
          claimName: ray-lab-storage
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - configMap:
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
      - configMap:
          defaultMode: 420
          name: ray-lab-kube-rbac-proxy-config
        name: kube-rbac-proxy-config
      - name: kube-rbac-proxy-tls-certificates
        secret:
          defaultMode: 420
          secretName: ray-lab-kube-rbac-proxy-tls
